"""Remove user_id and relationship from Service/Product model

Revision ID: 8e5b3e8384d4
Revises: d36a6dd4e4c0
Create Date: 2024-12-04 00:13:29.755847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5b3e8384d4'
down_revision: Union[str, None] = 'd36a6dd4e4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
