"""Remove users relationship from Service/Product model

Revision ID: 8fe9a9a74f53
Revises: 8e5b3e8384d4
Create Date: 2024-12-04 00:15:26.374699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe9a9a74f53'
down_revision: Union[str, None] = '8e5b3e8384d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
