"""Fix RolePermission relationships

Revision ID: d36a6dd4e4c0
Revises: 09ed058c4f23
Create Date: 2024-12-04 00:08:38.591620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36a6dd4e4c0'
down_revision: Union[str, None] = '09ed058c4f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'role_permissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('role_permissions', 'user_id')
    # ### end Alembic commands ###
